[package]
authors = ["bunnie <bunnie@kosagi.com>"]
description = "Xous microkernel OS inter-process name resolution server"
edition = "2018"
name = "xous-swapper"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/betrusted-io/xous-core/"
homepage = "https://betrusted.io/"

# Dependency versions enforced by Cargo.lock.
[dependencies]
xous-api-names = "0.9.63"
log-server = { package = "xous-api-log", version = "0.1.61" }
xous = { version = "0.9.64", features = ["swap"] }
xous-ipc = "0.10.2"
num-derive = { version = "0.3.3", default-features = false }
num-traits = { version = "0.2.14", default-features = false }
log = "0.4.14"
loader = { path = "../../loader", features = ["swap"] }
aes-gcm-siv = { version = "0.11.1", default-features = false, features = [
    "aes",
] }
cramium-hal = { path = "../../libs/cramium-hal", optional = true, default-features = false }

utralib = { version = "0.1.25", optional = true, default-features = false }

[target.'cfg(any(windows,unix))'.dependencies]

[features]
cramium-soc = ["utralib/cramium-soc", "cramium-hal", "loader/cramium-soc"]
cramium-fpga = ["utralib/cramium-fpga"]
board-baosec = ["cramium-hal/board-baosec"]
board-baosor = ["cramium-hal/board-baosor"]
board-dabao = ["cramium-hal/board-dabao"]

precursor = ["utralib/precursor"]
hosted = ["utralib/hosted"]
renode = ["utralib/renode"]
swap-userspace-testing = []
oom-doom = []

debug-print = []
debug-verbose = []
default = ["debug-print"]
